version: '3'

networks:
  coinboot:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.1.0/24

services:
  coinboot:
    container_name: coinboot
    env_file:
      - ./conf/environment/default.env
    environment:
      KERNEL: $KERNEL
    build: ./docker/
    volumes:
      - ./conf/dnsmasq:/etc/dnsmasq.d
      - ./conf/environment/:/srv/environment
      - ./boot:/var/lib/tftpboot
      - ./plugins:/srv/plugins
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      coinboot:
        ipv4_address: 192.168.1.2
