#!/bin/sh -e
#set -x

# Copyright (C) 2018 Gunter Miegel coinboot.io
#
# This file is part of Coinboot.
#
# Coinboot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# The Graylog content pack with the inputs for collection of the log messages from iPXE
# and the kernel need to be activated or applied how Graylog calls it.
# This is not happening by the "Content Pack Autoloader" of Graylog during startup due the
# uncoordinated startup sequence of Elasticsearch, MongoDB and Graylog by Docker Compose which
# is leading to a race condtion.
# So we use this small helper script to trigger this action via the REST-API of Graylog.

GRAYLOG=localhost:9000

# Get the id of the content pack
# Wait until the Graylog API is ready and returing the id

unset id

while [ -z $id ]; do
  id=$(curl --silent -u admin:admin http://$GRAYLOG/api/system/bundles |
    jq -r '.["Coinboot remote logging"] | .[] | .id ')
  echo  'Waiting for Graylog...'
  sleep 2
done


curl --silent -u admin:admin -X POST -H 'X-Requested-By: cli' http://$GRAYLOG/api/system/bundles/$id/apply
echo 'Content pack for Coinboot apllied.'
