#!/bin/bash -e

# Copyright (C) 2018 Gunter Miegel coinboot.io
#
# This file is part of Coinboot.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#
# Please notice even while this script is licensed with the
# MIT license the software packaged by this script may be licensed by
# an other license with different terms and conditions.
# You have to agree to the license of the packaged software to use it.


# Install the Prometheus node exporter

create_plugin.py start

sudo echo 'deb http://cz.archive.ubuntu.com/ubuntu/ eoan universe'|sudo tee /etc/apt/sources.list.d/eoan_universe.list
sudo echo 'Package: * Pin: release n=eoan Pin-Priority: 50'|sudo tee /etc/apt/preferences.d/eoan
sudo apt update
sudo apt-get install --no-install-recommends --yes prometheus-node-exporter/eoan
sudo systemctl enable prometheus-node-exporter.service
sudo rm /etc/apt/preferences.d/eoan

create_plugin.py finish $0_$(date +%Y%m%d.%H%M)
