---
version: '3'

volumes:
  grafana-data:

services:
  coinboot:
    image: coinboot/coinboot
    container_name: coinboot
    # "Values in the shell take precedence over those specified in the .env file."
    # https://docs.docker.com/compose/environment-variables/#the-env-file
    environment:
      KERNEL: $KERNEL
      RELEASE: $RELEASE
    env_file:
      - ./conf/environment/default.env
    volumes:
      - ./conf/dnsmasq:/etc/dnsmasq.d
      - ./conf/environment/:/srv/environment
      - ./boot:/var/lib/tftpboot
      - ./plugins:/srv/plugins
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    network_mode: "host"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - grafana-data:/var/lib/grafana
      - ./conf/grafana/provisioning:/etc/grafana/provisioning
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./conf/loki/loki.yaml:/etc/loki/loki.yaml
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
  # Fluent Bit is used as forwarder for UDP Syslog log messages to Loki
  #fluent-bit:
  #  image: fluent/fluent-bit:1.6.3
  #  container_name: fluent-bit
  #  entrypoint: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
  #  ports:
  #    - "514:514/udp"
  #    - "5140:5140/udp"
  #    - "5555:5555/udp"
  #  volumes:
  #    - ./conf/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
  # Fluentd is used as forwarder for UDP Syslog log messages to Loki
  fluentd:
    image: grafana/fluent-plugin-loki:master
    container_name: fluentd
    command: fluentd -p /fluentd/plugins
    environment:
      LOKI_URL: http://loki:3100
      LOKI_USERNAME:
      LOKI_PASSWORD:
    ports:
      # We have to map to unprivileged port 5140
      # because inside the container fluentd is running unprivileged
      - "514:5140/udp"
      - "5555:5555/udp"
    volumes:
      - ./conf/fluentd/fluentd.conf:/fluentd/etc/fluent.conf
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
