---
version: '3'

volumes:
  grafana-data:
  influxdb-data:

services:
  coinboot:
    image: coinboot/coinboot
    container_name: coinboot
    # "Values in the shell take precedence over those specified in the .env file."
    # https://docs.docker.com/compose/environment-variables/#the-env-file
    environment:
      KERNEL: $KERNEL
      RELEASE: $RELEASE
    env_file:
      - ./conf/environment/default.env
    volumes:
      - ./conf/dnsmasq:/etc/dnsmasq.d
      - ./conf/environment/:/srv/environment
      - ./boot:/var/lib/tftpboot
      - ./plugins:/srv/plugins
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    network_mode: "host"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./conf/grafana/provisioning:/etc/grafana/provisioning
      - ./conf/grafana/dashboards:/var/lib/grafana/dashboards
        #logging:
        #  driver: loki
        #  options:
        #    loki-url: "http://localhost:3100/loki/api/v1/push"
  influxdb:
    image: influxdb:2.0.4
    container_name: influxdb
    ports:
      - "8086:8086"
    command: " --reporting-disabled"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: Aish5Rae8jeezaeg
      DOCKER_INFLUXDB_INIT_ORG: coinboot.io
      DOCKER_INFLUXDB_INIT_BUCKET: telegraf
      V1_DB_NAME: telegraf
      #DOCKER_INFLUXDB_INIT_RETENTION: 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: sahKoh8Jalooyael
    volumes:
      - influxdb-data:/root/.influxdbv2
      - ./conf/influxdb/config.yml:/etc/influxdb2/config.yml
      - ./conf/influxdb/scripts/:/docker-entrypoint-initdb.d
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./conf/loki/loki.yaml:/etc/loki/loki.yaml
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
  fluentd:
    image: grafana/fluent-plugin-loki:master
    container_name: fluentd
    command: fluentd -p /fluentd/plugins
    environment:
      LOKI_URL: http://loki:3100
      LOKI_USERNAME:
      LOKI_PASSWORD:
    ports:
      # We have to map to unprivileged port 5140
      # because inside the container fluentd is running unprivileged
      - "514:5140/udp"
      - "5555:5555/udp"
    volumes:
      - ./conf/fluentd/fluentd.conf:/fluentd/etc/fluent.conf
      - grafana-data:/var/lib/grafana
      - ./conf/grafana/provisioning:/etc/grafana/provisioning
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
