---
version: '3'

volumes:
  grafana-data:

services:
  coinboot:
    image: coinboot/coinboot
    container_name: coinboot
    # "Values in the shell take precedence over those specified in the .env file."
    # https://docs.docker.com/compose/environment-variables/#the-env-file
    environment:
      KERNEL: $KERNEL
      RELEASE: $RELEASE
    env_file:
      - ./conf/environment/default.env
    volumes:
      - ./conf/dnsmasq:/etc/dnsmasq.d
      - ./conf/environment/:/srv/environment
      - ./boot:/var/lib/tftpboot
      - ./plugins:/srv/plugins
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    network_mode: "host"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - grafana-data:/var/lib/grafana
      - ./conf/grafana/provisioning:/etc/grafana/provisioning
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./conf/loki/loki.yaml:/etc/loki/loki.yaml
  # Fluent Bit is used as forwarder for UDP Syslog log messages to Loki
  fluent-bit:
    image: fluent/fluent-bit:1.6.3
    container_name: fluent-bit
    entrypoint: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
