#!/bin/sh -e

# debirf module: x1_motd

# Copyright (C) 2018 Gunter Miegel coinboot.io
#
# This file is part of Coinboot.
#
# Coinboot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


cat <<EOF > "${DEBIRF_ROOT}/etc/motd"
 [0;1;35;95m⢀[0;1;31;91m⣀[0m [0;1;33;93m⢀⡀[0m [0;1;32;92m⠄[0m [0;1;36;96m⣀[0;1;34;94m⡀[0m [0;1;35;95m⣇⡀[0m [0;1;31;91m⢀[0;1;33;93m⡀[0m [0;1;32;92m⢀⡀[0m [0;1;36;96m⣰[0;1;34;94m⡀[0m   [0;1;31;91m⠄[0m [0;1;33;93m⢀⡀[0m
 [0;1;31;91m⠣[0;1;33;93m⠤[0m [0;1;32;92m⠣⠜[0m [0;1;36;96m⠇[0m [0;1;34;94m⠇[0;1;35;95m⠸[0m [0;1;31;91m⠧⠜[0m [0;1;33;93m⠣[0;1;32;92m⠜[0m [0;1;36;96m⠣⠜[0m [0;1;34;94m⠘[0;1;35;95m⠤[0m [0;1;31;91m⠶[0m [0;1;33;93m⠇[0m [0;1;32;92m⠣⠜[0m

$VERSION $RELEASE
Created and maintained by Gunter Miegel
Contact: info@coinboot.io
EOF
