---


jobs:
  include:
    - &build_and_run
      env: KERNEL=4.15.0-43-generic SUITE=xenial
      stage: build and run
      dist: trusty
      sudo: required
      language: bash
      script: ./build_and_run
      after_success:
        - git config --global user.email "build@travis-ci.com"
        - git config --global user.name "Travis CI"
        - git tag -a "$(date +'%Y%m%d')" -m 'Automatic release by Travis CI'
        - git push "https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}".git --tags
        - git fetch origin
        - git tag
      deploy:
        provider: releases
        api_key: ${TOKEN}
        file_glob: true
        file: build/*
        skip_cleanup: true
        on:
          branch: master
        draft: true
    - <<: *build_and_run
      env: KERNEL=4.15.0-45-generic SUITE=xenial
    - <<: *build_and_run
      env: KERNEL=5.0.0-13-generic SUITE=disco
    - stage: publish
      script: skip
      deploy:
        provider: releases
        api_key: ${TOKEN}
        file_glob: true
        file: build/*
        skip_cleanup: true
        on:
          branch: master
        draft: false
