#!/bin/bash -e

# Create a plugin archive to make the machine act as Vagrant box.
# TODO: Try to achive most of this only by vagrant settings.

create_plugin start

useradd -m -p $(openssl passwd -1 vagrant) -s /bin/bash -G sudo vagrant

echo "vagrant ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/vagrant

mkdir /home/vagrant/.ssh

echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key' | sudo tee /home/vagrant/.ssh/authorized_keys

sudo chown vagrant:vagrant -R /home/vagrant/.ssh

sudo chmod -R 700 /home/vagrant/.ssh
sudo chmod -R 600 /home/vagrant/.ssh/authorized_keys

sudo apt update
sudo apt install virtualbox-guest-utils --no-install-recommends --yes

create_plugin finish coinboot-vagrantbox
