#!/bin/bash -e

create_plugin start

ETH_ADDRESS=<add your Etherium-ID here>
RIG_NAME=coinboot
ETHMINER_RELASE=0.13.0
ETHMINER_ARCHIVE=ethminer-$ETHMINER_RELASE-Linux.tar.gz
ETHMINER_URL=https://github.com/ethereum-mining/ethminer/releases/download/v$ETHMINER_RELASE/$ETHMINER_ARCHIVE
NAME=ethminer-$ETHMINER_RELASE
WGET='wget'

apt install $WGET --yes --no-install-recommends

if ! [ -f /tmp/$ETHMINER_ARCHIVE ]; then
  wget --progress=bar:force \
   $ETHMINER_URL -P /tmp
else
  echo "$ETHMINER_ARCHIVE is already downloaded."
fi

if ! [ -f /tmp/$ETHMINER_RELASE ]; then
  tar -zxvf /tmp/$ETHMINER_ARCHIVE -C /tmp
else
  echo "$ETHMINER_ARCHIVE is already decompressed."
fi

if ! [ -f "/usr/local/bin/ethminer" ]; then
 cp -r "/tmp/bin/ethminer" "/usr/local/bin/"
else
  echo "ethminer $ETHMINER_RELASE binary is already copied to the chroot."
fi

cat <<EOF > "/etc/systemd/system/ethminer.service"
[Unit]
Description=ethminer Ethereum Minining Software
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ethminer --report-hashrate -HWMON --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O $ETH_ADDRESS.$RIG_NAME
Restart=on-failure

[Install]
WantedBy=multi-user.target

EOF

# Disable variable expansion by quoting the label
# of the here-doc.
cat <<'EOF' > "/usr/local/bin/ethminerctl"
#!/bin/bash
# Small helper script for interacting with the ethminer
# Systemd unit.

case "$1" in
  start)
    sudo systemctl start ethminer
    ;;
  stop)
    sudo systemctl stop ethminer
    ;;
  status)
    sudo systemctl status ethminer
    ;;
  log)
    # '--output cat' is used to restore colors.
    sudo journalctl -fu ethminer --output cat
    ;;
esac

EOF

chmod a+x "/usr/local/bin/ethminerctl"

create_plugin finish coinboot-$NAME
