---
name: build_and_run
on: [push]
jobs:
  build_and_run:
    runs-on: ubuntu-20.04
    steps:
      - env:
          KERNEL: 4.15.0-72-generic
          SUITE: xenial
        uses: actions/checkout@v2
        run: pwd && ls
