---
name: build_and_run
on: [push]
jobs:
  build_and_run:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - kernel: "4.15.0-72-generic"
            suite: "xenial"
          - kernel: "5.3.0-29-generic"
            suite: "eoan"
    steps:
      - uses: actions/checkout@v2
      - env:
          KERNEL: ${{ matrix.kernel }}
          SUITE: ${{ matrix.suite }}
        run: ./debirf/build_and_run_images
